---
标题: pulseIn()
分类: [ "功能" ]
子标题: [ "高级 输入/输出" ]
---





= pulseIn()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 描述
从一个引脚读取脉冲(无论`HIGH`还是`LOW`)。 例如， 如果值是`HIGH`， `pulseIn()`等待引脚从`LOW`变为`HIGH`，开始计时，然后等待引脚变为`LOW`并停止计时。 返回脉冲长度（毫秒数）或者返回0如果在超时时间内没有接收到完整的脉冲（放弃了）。

这个函数的时间是个经验值，如果超长，将可能显示错误。 支持10毫秒到3分钟长度的脉冲。

注意：如果设置了可选的timeout参数，代码会执行得更快。
[%hardbreaks]


[float]
=== 句法
`pulseIn(pin, value)` +
`pulseIn(pin, value, timeout)`


[float]
=== 参数
`pin`: 你想读取脉冲的Arduino引脚编号。允许的数据类型: `int`. +
`value`: 脉冲读取类型: 无论链接:../../../variables/constants/constants[HIGH]还是链接:../../../variables/constants/constants[LOW]。允许的数据类型: `int`。 +
`timeout` (可选): 等待脉冲启动的毫秒数； 默认为1秒。 允许的数据类型: `unsigned long`。


[float]
=== 返回值
脉冲长度 (毫秒) ，或者0如果在超时前没有启动脉冲的话。数据类型: `unsigned long`.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== 示例代码
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
The example prints the time duration of a pulse on pin 7.

[source,arduino]
----
int pin = 7;
unsigned long duration;

void setup() {
  Serial.begin(9600);
  pinMode(pin, INPUT);
}

void loop() {
  duration = pulseIn(pin, HIGH);
  Serial.println(duration);
}
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== 查看其它

--
// SEE ALSO SECTION ENDS
